# Generated by Django 3.0.5 on 2020-05-13 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_auto_20200512_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttoperson',
            old_name='wawg',
            new_name='w_awg',
        ),
        migrations.RenameField(
            model_name='producttoperson',
            old_name='wmax',
            new_name='w_max',
        ),
        migrations.RenameField(
            model_name='producttoperson',
            old_name='wmin',
            new_name='w_min',
        ),
    ]
