# Generated by Django 3.0.5 on 2020-05-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0004_auto_20200513_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttoperson',
            name='weights',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='producttoperson',
            name='intakes_list',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='producttoperson',
            name='w_typ',
            field=models.TextField(default='[]'),
        ),
    ]
