# Generated by Django 3.0.5 on 2020-05-15 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0007_auto_20200513_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttoperson',
            old_name='w_awg',
            new_name='w_avg',
        ),
    ]
