# Generated by Django 3.0.5 on 2020-05-15 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0008_auto_20200515_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='producttoperson',
            name='is_fav',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProductToMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_product', to='foodapp.Product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='foodapp.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ManyToManyField(to='foodapp.ProductGroup'),
        ),
    ]
