# Generated by Django 3.0.5 on 2020-05-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0010_auto_20200515_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpair',
            name='ratio',
            field=models.IntegerField(null=True),
        ),
    ]
